### PR TITLE
Preliminary work for translating the Octane cheatsheet to French

### PR DESCRIPTION
**Pull request by bartocc**
This PR is an attempt to provide the `fr-fr` locale translations.

Looks like the logic to set the locale is not yet present in the repo. For the time being, this PR does not implement this logic.

I do not see any other translation files yet in the repo, so please let me know if this PR is not going in the right direction 🙏

### CODE REVIEW

**Comment by ijlee2** [comment]
@bartocc I think you are heading towards a right direction, certainly one that I had envisioned when I introduced `ember-intl`. 🧡

After our chat on Discord, I read `ember-intl` documentation to better understand how to support a multilingual site.

I thought of a couple of problems that we may run into. Let me document my thoughts here so that people can chime in to share ideas. Feel free to comment as well! (I don't think you need to address these problems in your PR.)

## Potential problems

1\. How do we detect when translations become out of sync, especially when a contributor writes a new section in English. Is there a way to indicate on the website that this new section hasn't been translated to other languages yet?

I wonder if a [`nested folder structure`](https://ember-intl.github.io/ember-intl/docs/guide/translating-text#nested-translations) for translations could help us detect new additions.

```
/translations <-- includes translations for "layout" and "component"
  en-us.yaml
  fr-fr.yaml
  /generating-files <-- includes translations for the section called "Generating Files"
    en-us.yaml
    fr-fr.yaml
  /component-templates <-- includes translations for the section called "Component Templates"
    en-us.yaml
    fr-fr.yaml
  ...
  /some-new-section
    en-us.yaml <-- aha! fr-fr.yaml is missing, so we need to translate this file
```


The chapter called [`Missing translations`](https://ember-intl.github.io/ember-intl/docs/guide/missing-translations) described how we might implement an error handler. Maybe we can create an error handler that looks for the English translation first, before throwing an error? I'm not sure.

2\. Jen and I previously discussed that it may not be easy for a new contributor to remember to escape special characters. It looks like `v5.x` handles [escaping characters](https://ember-intl.github.io/ember-intl/docs/guide/migration-4-0-to-5-0#translations) a little differently, so it may be good to update `ember-intl` to the latest and address possible bugs now, rather than wait till later.

**Comment by bartocc** [comment]
Thanks for the feedback @ijlee2!

In order to avoid unnecessary work done in this PR, and help it get merged in an acceptable timeframe, are you OK with the idea that finishing `translations/fr-fr.yml` is the goal of this PR?

**Comment by ijlee2** [comment]
Yes, I think finishing the `fr-fr` translations is the right goal for this PR.

Dividing translations into nested folders, updating `ember-intl`, and adding the ability to switch locales, I can look into these after we merge your PR. It'd be great to have the `fr-fr` translations for testing, actually.

Thank you again for helping out!

**Comment by jenweber** [comment]
I am happy to merge in non-breaking, incremental work if it is helpful for the workflow of coordinating the remaining to-dos. Just let us know. Thanks again @bartocc for your work on this!

**Comment by ijlee2** [comment]
@bartocc I agree with @jenweber. Incremental PRs are great!

This weekend, I updated this app's dependencies and CI workflow. Just in case, will you rebase your branch so that you get to work with the latest code? (I didn't update `ember-intl` so I think you will be able to rebase without code conflict.)

**Comment by bartocc** [comment]
@ijlee2 @jenweber I've just rebased on the latest master, pushed 3 more translations and marked the PR as `ready for review` 👍

**Comment by ijlee2** [comment]
Looks good to me!

@jenweber I think it's okay that we leave `setLocale` code as is. As long as we don't deploy the site, users will still be able to read the cheatsheet in English. Leaving the code in also allows me and @bartocc to continue to easily experiment with supporting a multilingual site.

@bartocc After merging this PR, let me first work on updating `ember-intl` to `v5` and splitting the translation file into multiple files across nested folders. After the PR for these works is merged, you can continue with translation. Does this plan sound good with you? (Feel free to suggest ideas for an alternative.)

**Review by ijlee2 — APPROVED** [review]

**Comment by bartocc** [comment]
> @bartocc After merging this PR, let me first work on updating `ember-intl` to `v5` and splitting the translation file into multiple files across nested folders. After the PR for these works is merged, you can continue with translation. Does this plan sound good with you? (Feel free to suggest ideas for an alternative.)

Sounds good @ijlee2. Can you ping me here when the `splitting` and `ember-intl` work will be done so that I start translating again?

**Comment by ijlee2** [comment]
@bartocc Yep, I will let you know!

**Comment by ijlee2** [comment]
@bartocc I updated the folder structure of `/translations` and the English texts to be (hopefully) easier to translate. Please feel free to resume your work at any time.

When you resume, will you take a look at `/translations/generating-files/generating-component/en-us.yaml`? I updated the 2nd and 3rd sentences in English, so these will need to be translated to French again:

```yaml
In Octane, '<code>'ember generate component'</code>' skips creating the JavaScript file.
If you want the backing JavaScript class as well, include the '<code>'-gc'</code>' option.
```

(All other existing French translations can remain the same.)

Lastly, I added Percy snapshots for English and French translations. Because you had to fork this repo, when you open a (draft) PR, I'm not sure yet if you will be able to see changes in Percy snapshots (to help you check translations). If you run into a problem with Percy or have any other questions, don't hesitate to reach out to me and @jenweber at any time!

**Pull request merged**
