### PR TITLE
Added description inside metatag

### LINKED ISSUE #57: Add meta description for SEO
## Problem

A Lighthouse audit showed that we could improve our score by adding the meta description.

lighthouse

Please update `app/index.html` to include the following meta description:

```
See side-by-side examples of Ember Octane and Ember Classic
```

(I chose this description to match that in `package.json`. If there's a description that can help with SEO better, objectively, we can change the description in both `package.json` and `index.html`.)

## References

- https://moz.com/learn/seo/meta-description

### PR DESCRIPTION
**Pull request by abraaoduarte**

### CODE REVIEW

**Review by ijlee2 — APPROVED** [review]
💯

**Comment by ijlee2** [comment]
@abraaoduarte Thanks again for working on this issue!

Before I merge the PR, I wanted to check: When you log in to Hacktoberfest Dashboard, are you able to see your pull request? Something like:

sample dashboard

Wanted to make sure that the PR will count towards your Hacktoberfest contributions (if I merge it now, that is).

**Comment by ijlee2** [comment]
I merged a couple of other PRs today, and think we're okay with merging this as well!

**Comment by abraaoduarte** [comment]
@ijlee2 It's ok. I'am able to see this PR
Thanks

**Pull request merged**
